export enum EnumInputType {
  none = 0,
  textField = 1,
  textArea = 2,
  richTextEditor = 22,
  numberField = 15,
  numberFieldWithSelect = 16,
  autoComplete = 3,
  datePicker = 4,
  timePicker = 18,
  dateTimePicker = 5,
  dateRangePicker = 6,
  dateRangePickerWithSwitch = 7,
  select = 8,
  toggleButton = 9,
  toggleSwitch = 12,
  radio = 14,
  treeSelectLookup = 17,
  switch = 11,
  checkbox = 13,
  chips = 10,
  areaPicker = 19,
  pressureAreaPicker = 20,
  painAreaPicker = 21,
  slider = 23,
  file = 24,
  treeselect = 25,
  dateTimeCalculator = 26,
  dateTimeCalculatorRange = 27,
  tableSelect = 28,
  summary = 29,
  chipsWithRadioButtons = 30,
  colorPicker = 31,
  dateBeforeCalculator = 32,
  tableInput = 33,
  dateAfterCalculator = 34,
  dateAfterCalculatorWithDatePicker = 35,
  areaMarking = 36,

  doubleNumberField = 98,
  migrationField = 99,
  dateYearAgeRange = 100,
  usersSelectInput = 101,

  //special types
  odyometri_series_chart = 500,
}
